In [1]:
# Handling Missing data in Pandas.

In [2]:
import pandas as pd

In [11]:
import numpy as np

In [12]:
#This is our small data frame.
df=pd.DataFrame([[5,2.9,8],[1.5,np.NAN,np.NAN],[np.NAN,np.NAN,np.NAN],[np.NAN,6.2,23.]])

In [13]:
df

     0    1     2
0  5.0  2.9   8.0
1  1.5  NaN   NaN
2  NaN  NaN   NaN
3  NaN  6.2  23.0

In [18]:
# This function replaces all the NaN nul values by assigned integer e.g 0 in our case
df.fillna(0)

     0    1     2
0  5.0  2.9   8.0
1  1.5  0.0   0.0
2  0.0  0.0   0.0
3  0.0  6.2  23.0

In [20]:
#Replacing values column values 

df.fillna({0:-5,1:0,2:5})

     0    1     2
0  5.0  2.9   8.0
1  1.5  0.0   5.0
2 -5.0  0.0   5.0
3 -5.0  6.2  23.0

In [21]:
df

     0    1     2
0  5.0  2.9   8.0
1  1.5  NaN   NaN
2  NaN  NaN   NaN
3  NaN  6.2  23.0

In [22]:
df.fillna(df.mean())

      0     1     2
0  5.00  2.90   8.0
1  1.50  4.55  15.5
2  3.25  4.55  15.5
3  3.25  6.20  23.0

In [23]:
df

     0    1     2
0  5.0  2.9   8.0
1  1.5  NaN   NaN
2  NaN  NaN   NaN
3  NaN  6.2  23.0

In [26]:
df.fillna(method='ffill')

     0    1     2
0  5.0  2.9   8.0
1  1.5  2.9   8.0
2  1.5  2.9   8.0
3  1.5  6.2  23.0

In [28]:
df

     0    1     2
0  5.0  2.9   8.0
1  1.5  NaN   NaN
2  NaN  NaN   NaN
3  NaN  6.2  23.0

In [33]:
df=df.dropna()

In [35]:
#This is our small data frame.
df=pd.DataFrame([[5,2.9,8],[1.5,np.NAN,np.NAN],[np.NAN,np.NAN,np.NAN],[np.NAN,6.2,23.]])

In [36]:
df

     0    1     2
0  5.0  2.9   8.0
1  1.5  NaN   NaN
2  NaN  NaN   NaN
3  NaN  6.2  23.0

In [37]:
df.fillna({0:-1,1:0,2:1})

     0    1     2
0  5.0  2.9   8.0
1  1.5  0.0   1.0
2 -1.0  0.0   1.0
3 -1.0  6.2  23.0

In [38]:
df

     0    1     2
0  5.0  2.9   8.0
1  1.5  NaN   NaN
2  NaN  NaN   NaN
3  NaN  6.2  23.0

In [40]:
df.fillna(method='ffill') #carry forwards the first value alaways

     0    1     2
0  5.0  2.9   8.0
1  1.5  2.9   8.0
2  1.5  2.9   8.0
3  1.5  6.2  23.0

In [41]:
df

     0    1     2
0  5.0  2.9   8.0
1  1.5  NaN   NaN
2  NaN  NaN   NaN
3  NaN  6.2  23.0

In [42]:
df.fillna(method='bfill')

     0    1     2
0  5.0  2.9   8.0
1  1.5  6.2  23.0
2  NaN  6.2  23.0
3  NaN  6.2  23.0

In [43]:
df

     0    1     2
0  5.0  2.9   8.0
1  1.5  NaN   NaN
2  NaN  NaN   NaN
3  NaN  6.2  23.0

In [46]:
df=df.interpolate(method='time')  # uses linear interpolation

In [47]:
df

     0    1     2
0  5.0  2.9   8.0
1  1.5  4.0  13.0
2  1.5  5.1  18.0
3  1.5  6.2  23.0

In [48]:
#This is our small data frame.
df=pd.DataFrame([[5,2.9,8],[1.5,np.NAN,np.NAN],[np.NAN,np.NAN,np.NAN],[np.NAN,6.2,23.]])

In [49]:
df

     0    1     2
0  5.0  2.9   8.0
1  1.5  NaN   NaN
2  NaN  NaN   NaN
3  NaN  6.2  23.0

In [52]:
df=df.dropna(how='all')

In [53]:
df

     0    1    2
0  5.0  2.9  8.0

In [54]:
#This is our small data frame.
df=pd.DataFrame([[5,2.9,8],[1.5,np.NAN,np.NAN],[np.NAN,np.NAN,np.NAN],[np.NAN,6.2,23.]])

In [55]:
df.dropna(how='all')

     0    1     2
0  5.0  2.9   8.0
1  1.5  NaN   NaN
3  NaN  6.2  23.0

In [56]:
df

     0    1     2
0  5.0  2.9   8.0
1  1.5  NaN   NaN
2  NaN  NaN   NaN
3  NaN  6.2  23.0

In [57]:
df.dropna(thresh=1)

     0    1     2
0  5.0  2.9   8.0
1  1.5  NaN   NaN
3  NaN  6.2  23.0

In [60]:
df.dropna(thresh=3) # keep those rows that have atleast 3 non-null values.

     0    1    2
0  5.0  2.9  8.0